CREATE TABLE pokemon (
    id SERIAL PRIMARY KEY,
    tcgplayer_url TEXT,
    tcgplayer_updated_at DATE,
    tcgplayer_prices JSONB,
    tcgplayer_images JSONB,
    id_in_set TEXT,
    name TEXT,
    supertype TEXT,
    subtypes TEXT[],
    hp TEXT,
    types TEXT[],
    evolves_to TEXT[],
    rules TEXT,
    ability JSONB,
    attacks JSONB,
    weaknesses JSONB,
    resistances JSONB,
    retreat_cost TEXT[],
    converted_retreat_cost INTEGER,
    artist TEXT,
    rarity TEXT,
    flavor_text TEXT,
    national_pokedex_number INTEGER,
    image_url TEXT
  );
  
  INSERT INTO pokemon (
  tcgplayer_url,
  tcgplayer_updated_at,
  tcgplayer_prices,
  tcgplayer_images,
  id_in_set,
  name,
  supertype,
  subtypes,
  hp,
  types,
  evolves_to,
  rules,
  ability,
  attacks,
  weaknesses,
  resistances,
  retreat_cost,
  converted_retreat_cost,
  artist,
  rarity,
  flavor_text,
  national_pokedex_number,
  image_url
)
VALUES ()